### ISSUE TITLE
Publish Plugin to Gradle Plugins Portal

### ISSUE THREAD

**Issue by gildor** [Triple-T/gradle-play-publisher#379] opened 2018-07-13 09:12 UTC
Currently, gradle-play-publisher is not available on [Gradle Plugins Portal](https://plugins.gradle.org/)
This doesn't allow to use it with [plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block). 

This is especially important for [Kotlin-DSL](https://github.com/gradle/kotlin-dsl), because allows having type-safe DSL

To fix this you just should publish it. This is instruction - https://plugins.gradle.org/docs/submit

Current workaround: manually register gradle-play-publisher in settings.gradle using `pluginManagement` DSL

**Comment by SUPERCILEX** [comment] 2018-07-13 16:24
You don't have to mess with settings. Simply add it to your classpath and apply like any other plugin:
```kt
plugins {
    // ...
    id("com.github.triplet.play")
}
```

We're can't really upgrade yet because the plugins repo doesn't support snapshot builds and doesn't support publishing to maven local. We'll work around those at some point, but possibly not in time for v2.0.

Closing as duplicate of #154

**Closed by SUPERCILEX** 2018-07-13 16:24 UTC
