### ISSUE TITLE
Option to only UPLOAD APK

### ISSUE THREAD

**Issue by fabiozo** [Triple-T/gradle-play-publisher#208] opened 2017-04-05 12:50 UTC
Hi,

Nice library, I was able to integrate with our product easily.
Nevertheless I have requirement to only upload APK to Beta without publishing, ideally would to make a draft only.

Is this possible ?

Thanks

**Comment by Conexur** [comment] 2017-07-19 23:46
Hi:
As I know, Google don't allow you upload first APK with API, you need to do manually, then you can update it with the API.

**Comment by fabiozo** [comment] 2017-07-20 07:06
Hi @Conexur 

What I meant is the situation where you already have the app in Play Store, but we like to just upload APK to Beta and make a draft of that version.

Currently instead of uploading to Beta we push app to Alpha and during promotion to Beta we update text about what is new.

Thanks

**Comment by SUPERCILEX** [comment] 2018-05-23 17:45
Closing as duplicate of #252.

**Closed by SUPERCILEX** 2018-05-23 17:45 UTC
