### ISSUE TITLE
Option to configure app bundle/apk name to publish

### ISSUE THREAD

**Issue by nlgtuankiet** [Triple-T/gradle-play-publisher#517] opened 2019-02-16 01:19 UTC
**Is your feature request related to a problem? Please describe.**
Recently I update my android gradle plugin from 3.5.0-alpha02 to 3.5.0-alpha04, they change the default app bundle name from `app.aab` to `app-release.aab`. This cause an error when run `gradlew publishReleaseBundle`:
```
File '...\app\build\outputs\bundle\release\app.aab' specified for property 'bundle' does not exist.
```

**Describe the solution you'd like**
Options to configure bundle file name or file path like:
```
play {
    bundlePath = "./build/outputs/bundle/release/app-release.aab"
}
```

**Comment by SUPERCILEX** [comment] 2019-02-18 19:38
Duplicate of #516

**Closed by SUPERCILEX** 2019-02-18 19:38 UTC
