### ISSUE TITLE
error with gradle build tools 4.2.1

### ISSUE THREAD

**Issue by Themaapps** [Triple-T/gradle-play-publisher#957] opened 2021-05-24 18:19 UTC
I am currently using gradle play publisher 3.4.0 with gradle build tools 4.1.3

If I switch to new gradle build tools 4.2.1 with Gradle 6.7.1, the following error is logged:

Unable to find method ''void com.android.build.gradle.internal.dsl.BaseAppModuleExtension.onVariants(kotlin.jvm.functions.Function1)''
'void com.android.build.gradle.internal.dsl.BaseAppModuleExtension.onVariants(kotlin.jvm.functions.Function1)'

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by SUPERCILEX** [comment] 2021-05-24 18:22
You have to add `-agp4.2` to the plugin version. Example: 3.4.0-agp4.2

**Comment by SUPERCILEX** [comment] 2021-05-24 19:27
Actually, this seems like a duplicate of #955

**Closed by SUPERCILEX** 2021-05-24 19:27 UTC
Labels: bug
