### ISSUE TITLE
Google changed console - Plugin is not working more

### ISSUE THREAD

**Issue by prsolucoes** [Triple-T/gradle-play-publisher#207] opened 2017-03-30 16:23 UTC
Google changed console - Plugin is not working more

Today i see that Google Console changed APK upload part and plugin is not working more.

Can anyone help?

**Comment by bhurling** [comment] 2017-03-30 16:48
Can you send the errors you get?

**Comment by prsolucoes** [comment] 2017-03-30 16:50
Hi,

On console, i got:

```
:ubook:packageUbookRelease

:ubook:assembleUbookRelease

:ubook:generateUbookReleasePlayResources

:ubook:publishApkUbookRelease FAILED

BUILD FAILED
```

**Comment by bhurling** [comment] 2017-03-30 17:03
Could you run the tasks with `--stacktrace`?

**Comment by prsolucoes** [comment] 2017-03-30 18:40
Sure. Its here:

```
FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':ubook:publishApkUbookRelease'.

> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden

{

"code" : 403,

"errors" : [ {

"domain" : "androidpublisher",

"message" : "Version 152 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.",

"reason" : "multiApkShadowedActiveApk"

} ],

"message" : "Version 152 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."

}

* Try:

Run with --info or --debug option to get more log output.

* Exception is:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ubook:publishApkUbookRelease'.

at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)

at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)

at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)

at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)

at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)

at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)

at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)

at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)

at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)

at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)

at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)

at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)

at org.gradle.internal.Transformers$4.transform(Transformers.java:169)

at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)

at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)

at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)

at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)

at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)

at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)

at org.gradle.execution.taskgraph.ParallelTaskPlanExecutor.process(ParallelTaskPlanExecutor.java:50)

at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)

at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)

at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)

at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)

at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)

at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)

at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)

at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)

at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)

at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)

at org.gradle.internal.Transformers$4.transform(Transformers.java:169)

at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)

at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)

at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)

at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)

at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)

at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)

at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)

at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)

at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)

at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)

at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)

at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)

at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)

at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)

at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)

at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)

at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)

at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)

at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)

at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)

at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)

at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)

at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)

at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)

at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)

at org.gradle.util.Swapper.swap(Swapper.java:38)

at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)

at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)

at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)

at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)

at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)

at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)

at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)

at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)

at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)

at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)

at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)

at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)

at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)

at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)

Caused by: org.gradle.api.UncheckedIOException: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden

{

"code" : 403,

"errors" : [ {

"domain" : "androidpublisher",

"message" : "Version 152 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.",

"reason" : "multiApkShadowedActiveApk"

} ],

"message" : "Version 152 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."

}

at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)

at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)

at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)

at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)

at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)

at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)

at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)

at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)

at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)

... 70 more

Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden

{

"code" : 403,

"errors" : [ {

"domain" : "androidpublisher",

"message" : "Version 152 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.",

"reason" : "multiApkShadowedActiveApk"

} ],

"message" : "Version 152 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."

}

at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)

at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)

at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)

at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)

at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$execute.call(Unknown Source)

at de.triplet.gradle.play.PlayPublishApkTask.publishApks(PlayPublishApkTask.groovy:37)

at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)

... 77 more
```

**Comment by prsolucoes** [comment] 2017-03-30 18:43
As usually, im trying publish a new version of app:

```
versionCode 163
versionName '4.2.0'
```

But i dont know why this error happen.

My store details:

![screenshot 2017-03-30 15 42 28](https://cloud.githubusercontent.com/assets/395096/24520639/85c17982-155f-11e7-8268-81e0f7437a92.png)

**Comment by hram** [comment] 2017-03-30 19:01
I had the same error and fix it with cerren plugin version

**Comment by hram** [comment] 2017-03-30 19:09
You can see my last comment on issue #121 
This is dev console bug I guest.

**Comment by prsolucoes** [comment] 2017-04-13 03:52
I saw your post. But it didnt solved to me. How i will select an app version from library if it doesnt upload.

**Comment by lakeman** [comment] 2017-05-17 07:06
Can you see an apk with version code 152 in your play store "Artifact Library"?

**Comment by eirikwah** [comment] 2017-05-29 06:55
We were affected by this bug as well, but we were able to work around this issue by publishing to "beta" instead of "alpha".

In summary, this bug is triggered by having an APK in beta that is "superseded by production" and then trying to release to alpha. Even if using `untrackOld = true` as explained in #121.

[This comment on a similar issue for fastlane](https://github.com/fastlane/fastlane/issues/6791#issuecomment-303505214) explains what is happening, and also states that:

> There's an api to unassign versions of a track, I took a look at the code and I believe it can be fixed by clearing the earlier tracks if a later track has a greater version code, before uploading the new apk.

In other words: The same fix as #121, but applied even for the beta APKs when uploading to alpha, if the APKs in beta are "superseded by production".

So, as short as possible, here is how to reproduce:

1. Upload build "1" to beta track. (Using web UI or gradle-play-publisher.)
2. Upload build "2" to alpha track. (Using web UI or gradle-play-publisher.)
3. Promote build "2" from alpha to production, without going through beta. (Using web UI)
4. Using gradle and gradle-play-publisher: Build version "3" and try to upload it to the alpha track.

Using settings:

```
play {
    jsonFile = file('play_account.json.gitcrypt')
    track = 'alpha'
    uploadImages = false
    untrackOld = true       // Automatically deactivate any shadowed APKs
}
```

The error message will be:

```
Execution failed for task ':someappname:publishApkVariantRelease'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Version 2 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.",
      "reason" : "multiApkShadowedActiveApk"
    } ],
    "message" : "Version 2 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."
  }
```

PS: I admit that this could be seen as a bug in the Google Play Console API, but I hope this would be possible to fix in gradle-play-publisher. Thanks!

**Comment by michaelbukachi** [comment] 2017-06-02 17:14
@eirikwah so what's the current workaround for this issue?

**Comment by eirikwah** [comment] 2017-06-06 20:51
@michaelbukachi The workaround we use at my team is possible because we do not need to release to alpha every time. Our workaround is simply to change `track = 'alpha'` into `track = 'beta'`.

**Comment by SUPERCILEX** [comment] 2018-05-24 02:15
Is anyone still experiencing this issue? I remember running into something similar and having to manually upload an APK to get things working again, but I haven't run into that bug in a while.

**Comment by bhurling** [comment] 2018-05-24 06:05
I believe it has been fixed in the Google console when they introduced notion of "superseded by"

**Comment by bhurling** [comment] 2018-05-24 06:06
Please reopen if you're running into this again

**Closed by bhurling** 2018-05-24 06:05 UTC
Labels: bug
