### ISSUE TITLE
error uploading multiple apk

### ISSUE THREAD

**Issue by maxbax** [Triple-T/gradle-play-publisher#195] opened 2017-03-16 18:00 UTC
I'm uploading manually 7 apk (on for abi from different flavors). I'd like to do this with your library, but after the first uploaded, on the second I receive the error (manually I have no errors):
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Devices with version 31037807 of this app would be downgraded to version 31037802 if they met the following criteria: [(API_LEVEL in range 15-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[arm64-v8a]] AND FEATURES containing all of [android.hardware.screen.PORTRAIT, android.hardware.FAKETOUCH])].",
      "reason" : "multiApkDowngradedDevice"
    } ],
    "message" : "Devices with version 31037807 of this app would be downgraded to version 31037802 if they met the following criteria: [(API_LEVEL in range 15-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[arm64-v8a]] AND FEATURES containing all of [android.hardware.screen.PORTRAIT, android.hardware.FAKETOUCH])]."
  }

  The versions of the apks are the following:

31037801
31037802
31037803
31037804
31037805
31037806
31037807
31037808
31037809

the library upload only one of these.

Manually I set active advanced mode and I upload each apk and at the end I publish all. 

Any suggestions?
Thanks

**Comment by bhurling** [comment] 2017-03-20 21:46
Could you explain what ABIs get what version codes? You said that you're creating 7 APKs but I see nine different version codes. It could also help to show how you calculate the version codes.

**Comment by maxbax** [comment] 2017-03-22 12:58
Thanks for your response. I've 7 ABI (the last two are used for debug only):
mips, arm, armv7, x86, mips64, x86_64 and arm64v8
The versionCode is calculated with a gradle function AAABBBCC, where:
AAA = version name (actual is 310)
BBB = version code (progressive number)
CC = abi number (example: mips=01, arm=02, and so on)

**Comment by bhurling** [comment] 2017-03-22 18:15
Maybe it's a typo? The error message complains about `arm64v8a`. You are using `arm64v8` (the trailing 'a' is missing).

**Comment by michaelbukachi** [comment] 2017-06-02 16:28
I'm also getting this error when I try to upload multiple apks. Could the reason be because of the new updates mad to google play console?

**Comment by AndreSand** [comment] 2017-10-02 03:37
Correct me if I'm wrong: with this error means that using gradle-play-publisher triplet we can't upload APKs for different CPU architectures?

**Comment by minhtc** [comment] 2017-10-23 13:09
same to me

```
[!] Google Api Error: multiApkDowngradedDevice: Devices with version 1048907 of this app would be downgraded to version 1048900 if they met the following criteria: [(API_LEVEL in range 16-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[armeabi-v7a]] AND GL_ES_VERSION in range 131072-0 AND FEATURES containing all of [android.hardware.screen.PORTRAIT, android.hardware.MICROPHONE, android.hardware.FAKETOUCH, android.hardware.BLUETOOTH, android.hardware.camera.AUTOFOCUS, android.hardware.LOCATION, android.hardware.CAMERA])].
```

**Comment by TakuSemba** [comment] 2018-01-29 07:09
i got the same.

```
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Devices with version 10001 of this app would be downgraded to version 10 if they met the following criteria: [(API_LEVEL in range 15-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND FEATURES containing all of [android.software.leanback, android.hardware.faketouch])].",
      "reason" : "multiApkDowngradedDevice"
    } ],
    "message" : "Devices with version 10001 of this app would be downgraded to version 10 if they met the following criteria: [(API_LEVEL in range 15-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND FEATURES containing all of [android.software.leanback, android.hardware.faketouch])]."
  }
```

**Comment by gtcompscientist** [comment] 2018-05-25 14:56
This is a problem caused by a change to the Google upload management where they try to give you better feedback. You have to make sure that you are ordering your split version codes so that higher codes are ALWAYS more specific. Before they would just let you upload these even if they were going to be served to nobody.

If you think I've closed this in error, please provide the specific situation that you are setting up so we can verify that it's a problem with the plugin and not the API rejecting it legitimately.

**Closed by gtcompscientist** 2018-05-25 14:56 UTC
Labels: bug
