### ISSUE TITLE
publishApkRelease task missing (using com.android.tools.build:gradle:2.2.0-rc2)

### ISSUE THREAD

**Issue by yukuku** [Triple-T/gradle-play-publisher#166] opened 2016-09-13 08:39 UTC
It's similar to #157 but now Android Studio 2.2 is already at RC2.

I also want to thank you for your library, this has been very useful.

**Comment by outlying** [comment] 2016-09-14 13:46
It seems that it happened after buildToolsVersion upgrade. I was able to release my app yesterday but today, after some tweaks and version upgrades, I am missing release task

**Comment by vonox7** [comment] 2016-09-21 16:04
I can confirm that the gradle update from 2.1.3 to 2.2.0 (as the now released Android Studio 2.2 suggests) removes the two tasks:

### Gradle 2.1.3
bootstrapReleasePlayResources
generateReleasePlayResources
publishApkRelease
publishListingRelease
publishRelease

### Gradle 2.2.0
bootstrapReleasePlayResources
generateReleasePlayResources
publishListingRelease

**Comment by sasvarizoli** [comment] 2016-09-21 16:05
+1

**Comment by christianlanz** [comment] 2016-09-22 09:32
+1

**Comment by papauschek** [comment] 2016-09-22 13:31
+1

**Comment by ShagunParikh** [comment] 2016-09-27 09:53
+1
Solved by updating 'com.github.triplet.gradle:play-publisher:1.1.4' to **1.1.5**.
Gradle version is **2.2.0**

**Comment by doubleo2** [comment] 2017-02-28 00:04
I think this is a dupe of #145

**Closed** 2017-03-13 21:14 UTC
