### ISSUE TITLE
Uploading listing failing

### ISSUE THREAD

**Issue by macgills** [Triple-T/gradle-play-publisher#606] opened 2019-06-19 09:54 UTC
### Describe the bug

The listing for our app is failing to upload with a 500, see the build [here](https://travis-ci.org/kiwix/kiwix-android/builds/547613318)

![image](https://user-images.githubusercontent.com/3358282/59754486-1c4f3b80-927e-11e9-8b42-0a2821f3f1b2.png)

Thankfully it does actually upload to Alpha on the play store and does take the release notes however we are only providing English translation at the moment so there is a warning

`4 language translations missing: de-DE, fr-FR, it-IT, and tr-TR`

and the "whats new in this release textbox" has the English listing and

> \<de-DE\>
> Enter or paste your release notes for de-DE here
> \</de-DE\>

for the missing translations.
Plugin configuration:
```
play {
  enabled = true
  serviceAccountCredentials = file("../google.json")
  track = "alpha"
  releaseStatus = "draft"
  resolutionStrategy = "fail"
}
```

### How To Reproduce

you can check out https://github.com/kiwix/kiwix-android/tree/release or 7da84c0b9048959b2b32d7da5eaff3efff32c1ab ? The dummy keystore in the project can be used, the dummy google.json definitely not

#### Versions

- Gradle Play Publisher: 2.2.1
- Gradle Wrapper: 5.1.1
- Android Gradle Plugin: 3.4.1

#### Tasks executed

publishKiwixRelease

### Expected behavior

The task to complete successfully without a 500 and not fail the build

**Comment by SUPERCILEX** [comment] 2019-06-19 18:08
The stuff with the release notes is expected (that's what happens if you create a release manually). And the 500 is a duplicate of #597. There's not much I can do besides wait and hope Google will fix it.

**Closed by SUPERCILEX** 2019-06-19 18:08 UTC
Labels: bug

**Comment by gitterandgold** [comment] 2019-06-19 23:21
This reason for this image upload error is described here: [https://developer.android.com/google-play/resources/icon-design-specifications#instructions_for_api_users](https://developer.android.com/google-play/resources/icon-design-specifications#instructions_for_api_users).
As the date mentioned on the page is now passed, you should not get the error anymore. That said the new specification is **now automatically applied** to all icon upload, so make sure you follow the guidelines.

**Comment by macgills** [comment] 2019-06-20 08:40
@SUPERCILEX @gitterandgold thanks so much for the help
