### ISSUE TITLE
in multi flavor, whatsnew file ignored, not updating in Google play store

### ISSUE THREAD

**Issue by jc01rho** [Triple-T/gradle-play-publisher#255] opened 2018-03-20 17:10 UTC
it was working good in one flavor - multibranch structure.

but i've merged in one branch and multi flavor, it does not working whatsnew  updates lol

> #213 should be considered :)

**Comment by jc01rho** [comment] 2018-03-21 09:02
i think still referencing main/play/<LANG>/whatsnew even if app has flavors,

**Comment by SUPERCILEX** [comment] 2018-05-24 03:11
This looks like it's happening with variants or no, so closing as duplicate of #213.

**Closed by SUPERCILEX** 2018-05-24 03:11 UTC
Labels: bug
