### ISSUE TITLE
Publishing product flavors apk via cli uploads to different branch than intented

### ISSUE THREAD

**Issue by nishithkhanna** [Triple-T/gradle-play-publisher#704] opened 2019-09-24 07:16 UTC
Hello, So previously I mentioned the upload track for my app in play block. But then due to some reasons I wanted to upload it via cli and mention the track in that command. 
It worked for app which has single apk but it didn't work for app which uses product flavor.
The command I used was
``` 
./gradlew publishApk --track alpha --release-status completed --user-fraction 1
```
This worked without any issue for the app which didn't had any product flavors and it uploaded to alpha track as intended
But with the app with product flavor it uploaded to internal track instead of alpha track. 
For both these apps I removed track attribute in play block.

Plugin version - 2.4.1
Android Studio version - 3.5.0
Gradle - 5.6.2

**Comment by SUPERCILEX** [comment] 2019-09-24 17:19
Just checking, do you have `playConfigs`?

**Comment by nishithkhanna** [comment] 2019-09-24 17:50
Yes
```
playConfigs {
        nougat {
            commit = false
        }

        oreo26 {
            commit = false
        }
        oreo27 {
            commit = false
        }
        pie {
            commit = true
        }
    }
```

**Comment by SUPERCILEX** [comment] 2019-09-24 18:05
Dope, duplicate of #652

**Comment by SUPERCILEX** [comment] 2019-09-24 18:06
Oh wait, you're the same person! 😂 Yeah, it's going to be a pain to fix so I'm going to take a while, sorry.

**Closed by SUPERCILEX** 2019-09-24 18:05 UTC
Labels: bug

**Comment by nishithkhanna** [comment] 2019-09-24 18:07
Sorry I didn't know they were inter related wouldn't have reported if I knew

**Comment by SUPERCILEX** [comment] 2019-09-24 18:08
No worries 😊
