### ISSUE TITLE
App Store title limit is wrong

### ISSUE THREAD

**Issue by henningvs** [Triple-T/gradle-play-publisher#229] opened 2017-07-09 21:35 UTC
When building and uploading the application the following error occus:

```
* What went wrong:
Execution failed for task ':app:publishListingRelease'.
> File 'pt-BR -> title' has reached the limit of 30 characters

```
When going to the webinterface it is possible to input 50 characters instead of the named 30.

**Comment by ChristianBecker** [comment] 2017-07-10 08:07
Duplicate of #224 . Fixed by #225 . Release: tba.

**Closed by ChristianBecker** 2017-07-10 08:07 UTC
