### ISSUE TITLE
publishApkRelease task missing

### ISSUE THREAD

**Issue by the4thfloor** [Triple-T/gradle-play-publisher#157] opened 2016-07-10 21:16 UTC
Since build gradle version 2.2.0-alpha5 the publishApkRelease tasks are gone :-(

With `com.android.tools.build:gradle:2.2.0-alpha4` I have this tasks:

```
Play Store tasks
----------------
bootstrapDevAlphaPlayResources - Downloads the play store listing for the DevAlpha build. No download of image resources. See #18.
bootstrapDevReleasePlayResources - Downloads the play store listing for the DevRelease build. No download of image resources. See #18.
bootstrapProdAlphaPlayResources - Downloads the play store listing for the ProdAlpha build. No download of image resources. See #18.
bootstrapProdReleasePlayResources - Downloads the play store listing for the ProdRelease build. No download of image resources. See #18.
generateDevAlphaPlayResources - Collects play store resources for the DevAlpha build
generateDevReleasePlayResources - Collects play store resources for the DevRelease build
generateProdAlphaPlayResources - Collects play store resources for the ProdAlpha build
generateProdReleasePlayResources - Collects play store resources for the ProdRelease build
publishApkDevAlpha - Uploads the APK for the DevAlpha build
publishApkDevRelease - Uploads the APK for the DevRelease build
publishApkProdAlpha - Uploads the APK for the ProdAlpha build
publishApkProdRelease - Uploads the APK for the ProdRelease build
publishDevAlpha - Updates APK and play store listing for the DevAlpha build
publishDevRelease - Updates APK and play store listing for the DevRelease build
publishListingDevAlpha - Updates the play store listing for the DevAlpha build
publishListingDevRelease - Updates the play store listing for the DevRelease build
publishListingProdAlpha - Updates the play store listing for the ProdAlpha build
publishListingProdRelease - Updates the play store listing for the ProdRelease build
publishProdAlpha - Updates APK and play store listing for the ProdAlpha build
publishProdRelease - Updates APK and play store listing for the ProdRelease build
```

With `com.android.tools.build:gradle:2.2.0-alpha5` I have this tasks:

```
Play Store tasks
----------------
bootstrapDevAlphaPlayResources - Downloads the play store listing for the DevAlpha build. No download of image resources. See #18.
bootstrapDevReleasePlayResources - Downloads the play store listing for the DevRelease build. No download of image resources. See #18.
bootstrapProdAlphaPlayResources - Downloads the play store listing for the ProdAlpha build. No download of image resources. See #18.
bootstrapProdReleasePlayResources - Downloads the play store listing for the ProdRelease build. No download of image resources. See #18.
generateDevAlphaPlayResources - Collects play store resources for the DevAlpha build
generateDevReleasePlayResources - Collects play store resources for the DevRelease build
generateProdAlphaPlayResources - Collects play store resources for the ProdAlpha build
generateProdReleasePlayResources - Collects play store resources for the ProdRelease build
publishListingDevAlpha - Updates the play store listing for the DevAlpha build
publishListingDevRelease - Updates the play store listing for the DevRelease build
publishListingProdAlpha - Updates the play store listing for the ProdAlpha build
publishListingProdRelease - Updates the play store listing for the ProdRelease build
```

**Comment by ObjectiveTruth** [comment] 2016-07-11 06:32
Came here to comment on the same thing 😞. `Travis-CI` just gave me the error

https://travis-ci.org/ObjectiveTruth/UoitDCLibraryBooking/builds/143812602

I'm currently using `com.android.tools.build:gradle:2.2.0-alpha5`, have you tried `com.android.tools.build:gradle:2.2.0-alpha4` to see if any of the new `publishAPK***Release` tasks work as expected??

**Comment by peterhav** [comment] 2016-07-11 07:12
Please check and star this issue: https://code.google.com/p/android/issues/detail?id=213532
This was solved in alpha4 but returned in alpha5.

**Comment by ObjectiveTruth** [comment] 2016-07-11 14:03
This looks like a duplicate of #145

**Comment by Pitel** [comment] 2016-07-20 11:47
`alpha6` still have this issue

**Comment by rafaltra** [comment] 2016-07-26 12:35
If you want use the latest alpha6, you can write in `gradle.properties`
`android.useOldPackaging=true`
This is temporary fix, because it's alpha release and there's no reason to support it.

**Comment by bhurling** [comment] 2016-08-09 08:34
Duplicates #145

**Closed by bhurling** 2016-08-09 08:34 UTC

**Comment by dannyroa** [comment] 2016-12-16 01:09
I'm on `com.android.tools.build:gradle:2.2.3` and there are no `publishApk` tasks for build types with release signing config.

There are tasks for build types with debug config though.

**Comment by emce** [comment] 2017-03-05 22:12
+1 - same for me
